import {
  Folder,
  Book,
  StickyNote,
  LayoutGrid,
  Check,
  X,
  Pencil,
  Trash2,
  Sun,
  Moon,
  Monitor,
  Menu,
  Plus,
  ArrowLeft,
  ArrowUp,
  GripVertical,
  Image,
  PenTool,
  Code,
  Table,
  Paperclip,
  Download,
  Type,
  Bold,
  Italic,
  Underline,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Pilcrow,
  Quote,
  List,
  ListOrdered,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  ChevronDown,
} from 'lucide-react'

const ICONS = {
  folder: Folder,
  book: Book,
  note: StickyNote,
  board: LayoutGrid,
  check: Check,
  close: X,
  edit: Pencil,
  delete: Trash2,
  themeLight: Sun,
  themeDark: Moon,
  themeSystem: Monitor,
  menu: Menu,
  add: Plus,
  back: ArrowLeft,
  up: ArrowUp,
  grip: GripVertical,
  image: Image,
  sketch: PenTool,
  code: Code,
  table: Table,
  embed: Paperclip,
  download: Download,
  text: Type,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  heading4: Heading4,
  paragraph: Pilcrow,
  citation: Quote,
  bulletList: List,
  orderedList: ListOrdered,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  alignJustify: AlignJustify,
  chevronDown: ChevronDown,
} as const

export type IconName = keyof typeof ICONS

interface IconProps {
  name: IconName
  size?: string | number
  className?: string
}

export function Icon({ name, size = '1em', className }: IconProps) {
  const Component = ICONS[name]
  return <Component size={size} className={className} aria-hidden="true" focusable="false" />
}
